// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpBLhqX1CWNHZV_mnlVuAYxcBsGEKffWg',
    appId: '1:201930196047:web:d629ee089f80b8407c163a',
    messagingSenderId: '201930196047',
    projectId: 'myblog-30913',
    authDomain: 'myblog-30913.firebaseapp.com',
    storageBucket: 'myblog-30913.firebasestorage.app',
    measurementId: 'G-V3HCLKHWN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqvsaIQCHyN6CBUZKAC9pqzYneq4Cae-Q',
    appId: '1:201930196047:android:7d68ac534251c1597c163a',
    messagingSenderId: '201930196047',
    projectId: 'myblog-30913',
    storageBucket: 'myblog-30913.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAugVPHCSnl6MS6l8BHbaozQzHzdWq8BYk',
    appId: '1:201930196047:ios:14728166945fda2e7c163a',
    messagingSenderId: '201930196047',
    projectId: 'myblog-30913',
    storageBucket: 'myblog-30913.firebasestorage.app',
    iosBundleId: 'com.example.myblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAugVPHCSnl6MS6l8BHbaozQzHzdWq8BYk',
    appId: '1:201930196047:ios:14728166945fda2e7c163a',
    messagingSenderId: '201930196047',
    projectId: 'myblog-30913',
    storageBucket: 'myblog-30913.firebasestorage.app',
    iosBundleId: 'com.example.myblog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpBLhqX1CWNHZV_mnlVuAYxcBsGEKffWg',
    appId: '1:201930196047:web:30a5dbb4d71e0e2a7c163a',
    messagingSenderId: '201930196047',
    projectId: 'myblog-30913',
    authDomain: 'myblog-30913.firebaseapp.com',
    storageBucket: 'myblog-30913.firebasestorage.app',
    measurementId: 'G-JBZTEKJ3XS',
  );

}